version: '3.8'

services:
  web:
    container_name: matcher
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - matcher
    image: matcher
    command: ["./main"]
    volumes:
      - ./matcher:/matcher/

    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - matcher_network

  # nginx:
  #   container_name: matcher_nginx
  #   build:
  #     context: ./nginx
  #   image: matcher_nginx
  #   volumes:
  #     - static_volume:/matcher/staticfiles
  #     - media_volume:/matcher/mediafiles
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web
  #   networks:
  #     - matcher_network

  db:
    image: postgres:latest
    container_name: matcher_database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - matcher_network

volumes:
  static_volume:
  media_volume:
  postgres_data:

networks:
  matcher_network:
    driver: bridge
