services:
  database:
      image: postgres:latest
      container_name: ${POSTGRES_CONTAINER}
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      ports:
        - "${POSTGRES_PORT}:5432"
      volumes:
        - postgres_matcher_data:/var/lib/postgresql/db_data
      env_file:
        - .env

volumes:
  postgres_matcher_data: