services:
  cassandra:
    image: cassandra:latest
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_SEEDS=${CASSANDRA_SEEDS}
      - CASSANDRA_DC=${CASSANDRA_DC}
      - CASSANDRA_RACK=${CASSANDRA_RACK}
    ports:
      - "${CASSANDRA_PORT}:9042" # Port to connect to Cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep UN"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend-network
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  cassandra-data:
  redis-data:

networks:
  backend-network:
    driver: bridge
